#pragma config(Sensor, S1,     rightsonar,     sensorSONAR)
#pragma config(Sensor, S2,     lightsensor,    sensorLightInactive)
#pragma config(Sensor, S3,     front,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define PLACES "123"
#define CELLSIZE 40
#define BASELINE

task main()
{
  nxtDisplayCenteredTextLine(1, "MUXAMEDZZZ");
  nxtDisplayCenteredTextLine(2, "TEST PROGRAM!");

  motor[motorA] = 25;
  motor[motorB] = 25;

  //wait1Msec(4000);

  while(1)
  {
    wait1Msec(100);
    int r = SensorValue(rightsonar);
    nxtDisplayCenteredTextLine(3, "Distance = %f", r);

    if(r < 20)
    {
      motor[motorB] = 0;
    }
    else
    {
      motor[motorB] = 25;
    }

    if(r > 30)
    {
    	motor[motorA] = 0;
  	}
  	else
  	{
  		motor[motorA] = 25;
  	}

  }
}
